#!/usr/bin/env python3
"""Write assets/tile-data.js: the shapes the Open Mappr transition lays.

    python3 tools/build-tiles.py

Solid glazed tiles, thrown at amplitude 1.2 (board 07's loud setting, and the
fills ceiling is 1.6 so 1.2 has room). Six thrown squares so no two adjacent
tiles share an edge shape, plus the six motifs, knocked out in the ground.
Board 05's hand applies: sampled every 10 to 13px, round caps and joins.
"""
import json, os, random, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.chdir(os.path.dirname(os.path.abspath(__file__)))
from glaze import MOT, jitter, resample, path

BOX = 100.0
rnd = random.Random(7714)

def thrown_square(rnd):
    """A tile edge. Closed, so no overshoot: an overshoot is for open outlines."""
    e = BOX
    box = [(0, 0), (e, 0), (e, e), (0, e), (0, 0)]
    p = jitter(resample(box, rnd), rnd)
    p[-1] = p[0]
    return path(p)

data = {
    "tiles": [thrown_square(rnd) for _ in range(6)],
    "motifs": {k: v["paths"] for k, v in MOT.items()},
    "accents": ["#ff8787", "#ffa94d", "#ffd43b", "#69db7c", "#74c0fc", "#b197fc"],
    "ground": "#121212",
}
out = ("/* Generated by tools/build-tiles.py. Do not hand-edit. */\n"
       "window.ARGH_TILES=" + json.dumps(data, separators=(",", ":")) + ";\n")
open(os.path.join("..", "assets", "tile-data.js"), "w").write(out)
print(f"{len(data['tiles'])} tiles, {len(data['motifs'])} motifs, {len(out)} bytes")
