#!/usr/bin/env python3
"""Inline the critical CSS into both pages, taken from assets/site.css.

    python3 tools/build-critical.py

Writes between the <!--critical:start--> / <!--critical:end--> markers. It
extracts real rules from the stylesheet in source order, so the cascade and
any later override still apply and the two copies cannot drift from the
sheet the way a hand-written block does.

Critical means: enough to paint the page dark and roughly right above the
fold if site.css is late. Everything below the fold waits for the sheet.
"""
import os, re, sys

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

SHARED = [
    ':root', '*', 'html', 'body', 'a', 'a:hover', '.wrap', '.label',
    '.spectrum', '.spectrum span',
    '.spectrum .s1', '.spectrum .s2', '.spectrum .s3',
    '.spectrum .s4', '.spectrum .s5', '.spectrum .s6',
    '.topbar', '.topbar .inner', '.topbar .name', '.topbar .ver',
    '.topbar nav', '.topbar nav a', '.topbar nav a.argh', '.topbar nav a.cta',
    '.topbar nav a.cta.drawn', '.topbar nav a.cta.drawn .t',
    '.btn', '.btn-primary', '.btn-ghost',
    '.drawn', '.drawn .ed', '.drawn .ed svg', '.drawn .t', '.drawn .f2,.drawn .f3',
    '.btn.drawn.btn-primary', '.btn.drawn.btn-primary .t',
    '.btn.drawn.btn-ghost', '.btn.drawn.btn-ghost .t',
    '.grain', '.grain svg',
    '.tileband', '.tileband .row', '.tileband .bt', '.tileband .bt svg',
]
HOUSE = ['body.house', '.house .topbar .name', '.house .topbar nav a',
         '.hhero', '.hhero .glaze', '.hhero .wrap', '.hhero .label',
         '.hhero h1', '.hhero .lead', '.hhero .actions', '.hhero .reassure']
MAPPR = ['.hero', '.hero .label', '.hero h1', '.hero h1 .hl', '.hero .lead',
         '.hero .actions', '.hero .reassure', '.hero-note',
         '.panel', '.panel-bar', '.hero-panel', '.map-paper']

def rules(css):
    """(media, selector, body) in source order. One level of @media is enough."""
    out, i, n = [], 0, len(css)
    while i < n:
        at = css.find('@media', i)
        brace = css.find('{', i)
        if brace == -1:
            break
        if at != -1 and at < brace:
            depth, j = 0, css.index('{', at)
            k = j
            while k < n:
                if css[k] == '{': depth += 1
                elif css[k] == '}':
                    depth -= 1
                    if depth == 0: break
                k += 1
            q = css[at:j].strip()
            for _, sel, body in rules(css[j+1:k]):
                out.append((q, sel, body))
            i = k + 1
            continue
        end = css.find('}', brace)
        if end == -1: break
        sel = css[i:brace].strip()
        sel = re.sub(r'/\*.*?\*/', '', sel, flags=re.S).strip()
        out.append((None, sel, css[brace+1:end].strip()))
        i = end + 1
    return out

def build(wanted, all_rules):
    want = set(wanted)
    base, med = [], {}
    for q, sel, body in all_rules:
        if sel not in want:
            continue
        body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)   # comments would bloat it
        line = sel + '{' + re.sub(r'\s*\n\s*', '', body).strip() + '}'
        if q is None: base.append(line)
        else: med.setdefault(q, []).append(line)
    parts = base[:]
    for q, lines in med.items():
        parts.append(q + '{' + ''.join(lines) + '}')
    return '\n'.join(parts)

css = open('assets/site.css').read()
R = rules(css)

for page, extra, label in (('index.html', HOUSE, 'house'),
                           ('mappr/index.html', MAPPR, 'Mappr')):
    block = ('<style>\n'
             '/* Critical: enough to paint dark and roughly right above the fold if\n'
             '   site.css is late. Generated by tools/build-critical.py from the\n'
             '   stylesheet itself; do not hand-edit. */\n'
             + build(SHARED + extra, R) + '\n</style>')
    s = open(page).read()
    if '<!--critical:start-->' not in s:
        s = s.replace('<link rel="stylesheet" href="/assets/site.css">',
                      '<!--critical:start-->\n<!--critical:end-->\n'
                      '<link rel="stylesheet" href="/assets/site.css">', 1)
    s = re.sub(r'(<!--critical:start-->).*?(<!--critical:end-->)',
               lambda m: m.group(1) + '\n' + block + '\n' + m.group(2), s, flags=re.S)
    open(page, 'w').write(s)
    print(f'{page:18} {label:6} critical block {len(block)} bytes')
